SELECT * FROM product;
-- INSERT INTO product (name, description, price, quantity, brand, category, image)
-- VALUES ('Dreamcast', 'Space gray', 100.00, 9999, 'Sega', 'Gaming Console', '/Stock_Images/dreamcast.jpg'),
--        ('FIFA 20', 'Best Selling Sports Game', 59.99, 9999, 'EA', 'Video Game', '/Stock_Images/fifa.jpg'),
--        ('iPod', '32GB', 200, 9999, 'Apple', 'Music Player', '/Stock_Images/ipod.jpg'),
--        ('Zune', '8GB', 100, 9999, 'Microsoft', 'Music Player', '/Stock_Images/zune.jpg'),
--        ('Red Dead Redemption 2', 'Best Video Game of 2018', 58.99, 15000, 'Rockstar', 'Video Game', '/Stock_Images/rdr2.jpg'),
--        ('iPhone X', '64GB, iOS 11, space gray', 999.00, 9999, 'Apple', 'Smart Phone', '/Stock_Images/iphonex.jpg'),
--        ('iPhone 8', '64GB, iOS 11, silver', 799.00, 9999, 'Apple', 'Smart Phone', '/Stock_Images/iphone8.jpg'),
--        ('C7 OLED', '65" Smart TV', 3000, 9999, 'LG', 'TV', '/Stock_Images/tv.jpg'),
--        ('Macbook Pro', '15 laptop, 512GB SSD', 2800, 15000, 'Apple', 'Computer', '/Stock_Images/macbook.jpg');
